### ISSUE TITLE
GPL Violation

### ISSUE THREAD

**Issue by SciresM** [SwitchFun/PayloadNX#1]
Hello,

Atmosphere is licensed as GPLv2. Please either relicense to a compatible open source license, or do not distribute Atmosphere binaries without source. 

Thank you! :)

**Comment by SwitchFun** [comment]
I have our pulled compiled binary until we re-write some of the atmosphere included source code. Sorry about this.

**Comment by SwitchFun** [comment]
I will be open sourcing the project.

**Comment by SwitchFun** [comment]
Licensing now complies.

Thank you!
